### ISSUE TITLE
what path works for localhost

### ISSUE THREAD

**Issue by hisusqristos** [MartinSStewart/best-color#3]
i ran the code with `elm reactor` then went to browser to see the result. the absence of Main.elm got me confused, so i attempted `http://localhost:8000/src/EVERY-FILE`, but nothing worked. please guide me

and also, running commands in the readme files would be really helpful :-)

**Comment by MartinSStewart** [comment]
Hi, this app was built with Lamdera. You can download the compiler here https://dashboard.lamdera.app/docs/download and then run `lamdera live` in the project root folder to run the app locally.

**Comment by hisusqristos** [comment]
Thank you
